### PR TITLE
example code snippets usage AEROGEAR-1643

### PR DESCRIPTION
**Pull request by lfryc**
https://issues.jboss.org/browse/AEROGEAR-1643

@abstractj @andresgalante could you review guys?

You can see it here: http://staging-aerogearsite.rhcloud.com/getstarted/guides/codesnippets.html

### CODE REVIEW

**Comment by lfryc** [comment]
The question is: is it simply enough to use?

**Comment by danielpassos** [comment]
:+1:  I like that

**Comment by abstractj** [comment]
@lfryc to me is easy to use. I'm not sure how html tags behave with asciidoc, thinking about our guides. If the behavior is the same like Markdown files +1

**Comment by lfryc** [comment]
thanks guys, I'll merge it, I will believe it will work for Markdown/asciidoc as it is, since you can always use pure HTML sections

**Comment by abstractj** [comment]
@lfryc from my knowledge we can't use asciidoc with HTML in the same document. Have managed to make it work?

**Comment by andresgalante** [comment]
@lfryc I agree with @abstractj I couldn't use html inside asciidoc. (thats a point to markdown by the way)

**Comment by lfryc** [comment]
Asciidoctor is able to include raw HTML blocks: http://mrhaki.blogspot.cz/2014/06/awesome-asciidoc-include-raw-html.html

**Comment by lfryc** [comment]
Merged here btw: https://github.com/aerogear/aerogear.org/commit/6e653b931da8b28d26b9e5ad7db5f80a975d3d7e

**Pull request closed without merging**
