### PR TITLE
Latest jazzy version for ios api doc

### PR DESCRIPTION
**Pull request by corinnekrych**
@edewit I've regenerated documentation with latest version of jazzy.it should fix the file name problem on Windows (I haven't test it though).
would you mind taking a look?

### CODE REVIEW

**Comment by edewit** [comment]
:eyes:

**Comment by edewit** [comment]
yeah the problem was with files that have `:` chars in the name, :+1: the new version no longer has that!

**Comment by matzew** [comment]
:+1:

**Comment by corinnekrych** [comment]
merged b859c823a0b6c89caed9867f7c087a0ef3601881

**Pull request closed without merging**
