### PR TITLE
first steps windows

### PR DESCRIPTION
**Pull request by edewit**
adding fist steps documentation for windows solving issue [AEROGEAR-1659](https://issues.jboss.org/browse/AEROGEAR-1659)

### CODE REVIEW

**Comment by edewit** [comment]
@lfryc something like this?

**Comment by lfryc** [comment]
I would also add something like: `Find more about what AeroGear offers for Windows at /windows/`, wdyt?

**Comment by edewit** [comment]
Good idea

**Comment by lfryc** [comment]
landed with the suggested improvement (aligned with iOS): https://github.com/aerogear/aerogear.org/commit/7c30798bbdfda97586d6d38d1c2cb41bbe548017

edewit++

**Pull request closed without merging**
