### PR TITLE
Guides polishing + generated TOC

### PR DESCRIPTION
**Pull request by lfryc**
Contains all the bits of: https://github.com/aerogear/aerogear.org/pull/518

Adds automatically generated TOC to Guides + some fixes to TOC generation engine was required.

Fixes:
* https://issues.jboss.org/browse/AEROGEAR-1552
* https://issues.jboss.org/browse/AEROGEAR-1637
* https://issues.jboss.org/browse/AEROGEAR-1649

### CODE REVIEW

**Comment by andresgalante** [comment]
@lfryc I don't know if it's a good idea to have a TOC on all guides. Some of them don't have enough structure or content like:
http://staging-aerogearsite.rhcloud.com/docs/guides/aerogear-android/AerogearAndroidPagination/
It does work excellent on UPS guides.

**Comment by lfryc** [comment]
@andresgalante sure, let's make auto-generated TOC configurable.

We should change the layout a bit based on whether the page has/hasn't TOC, right?

**Comment by lfryc** [comment]
@andresgalante I've addressed your concerns in last two commits

**Comment by abstractj** [comment]
@lfryc while rebasing against `new-design` I found some conflicts. Would you mind to fix, please?

**Comment by lfryc** [comment]
Thanks @abstractj , that's because I had to do a merge from Andres branch in my own branch.

:rocket: landed!

**Pull request merged**
