### PR TITLE
Refreshing the docs on the Android landing page

### PR DESCRIPTION
**Pull request by secondsun**

### CODE REVIEW

**Comment by secondsun** [comment]
@danielpassos @matzew :eyes: ?

**Comment by matzew** [comment]
I liked the 'old' description, it contained usful information, especially: AeroGear Android 2.0.0 supports Android 4.1 and higher. 

Mind adding that section back to the top (of the md file)?

**Comment by secondsun** [comment]
@matzew K

**Comment by matzew** [comment]
@secondsun @danielpassos looks good to me!

**Pull request merged**
