### PR TITLE
AGDroid Push 2.2.0

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
@matzew @secondsun Could you check if I missed something?

**Comment by secondsun** [comment]
@danielpassos I feel like https://aerogear.org/docs/guides/aerogear-android/push should include something about the metrics APIs.  wdyt?

**Comment by matzew** [comment]
@secondsun good point, but I already created a JIRA for @danielpassos on this subject: 

https://issues.jboss.org/browse/AGPUSH-1409

**Comment by matzew** [comment]
Ok folks, I have merged it to master (1f3223191fafc113826227e383b9cb2d835a2c46) and production (e359c96b9bb6f20f77723bae4b6a50dfa6d9b7cf) :tada:

**Pull request closed without merging**
