### PR TITLE
adding architecture diagram and sequence diagrams

### PR DESCRIPTION
**Pull request by sebastienblanc**
@matzew Could have a look ?

### CODE REVIEW

**Comment by matzew** [comment]
Hi @sebastienblanc 

I like the overview and the sequence diagrams! However I am not sure if the location is really a good fit here. The new 'Global Architecture' section feels a bit like added w/o too much context.

I am wondering if we should do a separate architecture file (or wiki)? 

Also, I thought the sequence diagrams could be nicely weaved into the text from the 'The Big Picture' section.

Regarding diagrams, I think @lfryc  has a diagram too.

Perhaps the new arch. diagram could be styled by @andresgalante to have the same look and feel like our overview diagram?

Just some thoughts on this before adding it.

**Comment by sebastienblanc** [comment]
@matzew I agree the location is a bit weird. We could have a separate file but what about having an "appendix" section in our guide containing these arch details? That would also make sense no ? 
And +1 to have @andresgalante make the diagrams sexy ;)

**Comment by matzew** [comment]
appendix for what? all? the overview? the sequence diagram ? 

I think the squence diagrams could be nicely added to the text on the big picuture section.

Appendix for the overview and @lfryc's diagram would be good

**Comment by lfryc** [comment]
Yea, I will create an issue to capture details / diagram for JMS related
inner workings.

**Comment by andresgalante** [comment]
@lfryc @sebastienblanc @matzew Should I make them following this style?
https://aerogear.org/docs/unifiedpush/ups_userguide//img/aerogear_unified_push_server.png

**Comment by matzew** [comment]
yes, that would be good. I think the graphic could be added to:
https://github.com/aerogear/aerogear-design

On Tue, May 26, 2015 at 2:35 PM, Andres Galante <notifications@github.com>
wrote:

> @lfryc <https://github.com/lfryc> @sebastienblanc
> <https://github.com/sebastienblanc> @matzew <https://github.com/matzew>
> Should I make them following this style?
>
> https://aerogear.org/docs/unifiedpush/ups_userguide//img/aerogear_unified_push_server.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/585#issuecomment-105509893>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by sebastienblanc** [comment]
@andresgalante yes and if you think it needs some extra polishing to match the new Aerogear website identity , feel free to do so (even for https://aerogear.org/docs/unifiedpush/ups_userguide//img/aerogear_unified_push_server.png )

**Comment by sebastienblanc** [comment]
@matzew yeah , keeping the sequence diagram in the general doc and having the overview + @lfryc diagram in the appendix.

**Comment by matzew** [comment]
adding to https://github.com/aerogear/aerogear.org/pull/597

**Pull request closed without merging**
