### PR TITLE
Jira powered roadmaps

### PR DESCRIPTION
**Pull request by matzew**
Next round of a few more JIRA powered roadmaps

### CODE REVIEW

**Comment by matzew** [comment]
@danielpassos @edewit @lholmquist @corinnekrych can you review ?

**Comment by edewit** [comment]
:+1: great stuff

**Comment by abstractj** [comment]
@matzew just updated with my roadmapen https://github.com/matzew/aerogear.org/pull/10. I'm working on some polishing

**Comment by matzew** [comment]
cool! I was planing on that for a next iteration :-) Especially I wanted to
double check on the `Future and beyond` listed items. E.g. which ones need
a future JIRA etc.

But, now I am merging your PR to be included :-)

On Wed, Feb 11, 2015 at 4:02 PM, Bruno Oliveira <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> just updated with my roadmapen
> matzew#10 <https://github.com/matzew/aerogear.org/pull/10>. I'm working
> on some polishing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/489#issuecomment-73894953>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by abstractj** [comment]
@matzew thank you, the future and beyond will be added for 2.future

**Comment by danielpassos** [comment]
:+1:

**Comment by abstractj** [comment]
@matzew landed, thanks

**Pull request closed without merging**
