### PR TITLE
AGSEC-204: Getting started page for OAuth2

### PR DESCRIPTION
**Pull request by abstractj**
Good morning, this is pretty much teamwork moved to the security section. To review all these changes, visit: http://cobblepot-abstractj.rhcloud.com/docs/guides/security/oauth2-guide/

The work was tracked here https://issues.jboss.org/browse/AGSEC-204.

- Next: I'm now moving to the Crypto section, but would like your feedback on it, once this change does not depend on that.

@lfryc @edewit @danielpassos @corinnekrych @cvasilak @secondsun you are all invited to review, once it refers to your project.

Thanks in advance.

### CODE REVIEW

**Comment by edewit** [comment]
:+1: great job

**Comment by cvasilak** [comment]
awesome job @abstractj, clean and easy to follow 

:+1:

**Comment by corinnekrych** [comment]
+1 great job.

just one question @abstractj : there is no mention of open id connect. Maybe it can be mentioned as WIP, or do you think it's too early?

**Comment by matzew** [comment]
@abstractj awesome job. I added a tiny small PR for some formatting issues https://github.com/abstractj/aerogear.org/pull/6

**Comment by abstractj** [comment]
@corinnekrych thank you, what would you like to see there? Something like:

```
  var Http = Http()
  let keycloakConfig = KeycloakConfig(
    clientId: "sharedshoot-third-party",
    host: "http://localhost:8080",
    realm: "shoot-realm",
    isOpenIDConnect: true)
```

Plus the paragraph from Authorization.asciidoc?

**Comment by abstractj** [comment]
@matzew thank you, updated.

**Comment by lfryc** [comment]
:+1: abstractj++!

Ready to merge?

**Comment by abstractj** [comment]
@lfryc go ahead, I talked with @corinnekrych on #aerogear. About OpenID, a Jira will be created to track the missing sections.

**Comment by lfryc** [comment]
Awesome, thanks! I will merge it in a bit..

**Comment by lfryc** [comment]
:rocket: landed: https://github.com/aerogear/aerogear.org/commit/c1b3cd3d19f0abe356c65f60bf06686a6769e6fc

**Pull request closed without merging**
