### PR TITLE
Adding OAuth2 table, based on release blog

### PR DESCRIPTION
**Pull request by matzew**
Based on our announcement last week, here is the same table.

Minor note: rendering looks better on github, than on our own hosted Jekyyl site ;-)

### CODE REVIEW

**Comment by matzew** [comment]
@abstractj mind to a reviewen ?

**Comment by edewit** [comment]
why not add cordova and windows?

**Comment by abstractj** [comment]
@edewit Is there, not checked yet. After review the stable releases of that we update the table and call it a day.

**Comment by matzew** [comment]
Let's get the open Windows/Cordova PRs in and release the libs to Corodova plugin reg. and Nugget (or what is the .NET repo?).

Once that and the cookbooks are also using latest greatest, let's have another simple announcment: Windows and Cordova is there (released), and at the same time, we will get the table updated

**Comment by edewit** [comment]
https://www.nuget.org/packages/aerogear-windows-oauth2/
http://plugins.cordova.io/#/package/org.jboss.aerogear.cordova.oauth2
https://github.com/aerogear/aerogear-cordova-cookbook/tree/master/Shoot

**Comment by matzew** [comment]
For Cordova, I see the Windows PR being open. Let's solve all the PRs, run
another round of releases (of the lastest greatest). Sounds reasonable ?

On Mon, Feb 9, 2015 at 4:31 PM, Erik Jan de Wit <notifications@github.com>
wrote:

> https://www.nuget.org/packages/aerogear-windows-oauth2/
> http://plugins.cordova.io/#/package/org.jboss.aerogear.cordova.oauth2
> https://github.com/aerogear/aerogear-cordova-cookbook/tree/master/Shoot
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/487#issuecomment-73527843>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by edewit** [comment]
why not have the window part of the table show the current released support?

**Comment by matzew** [comment]
Ah - now I get it :-)

can you update the PR for the correct support level, of what we already
supported on Windows/Cordova, with the releases ?

On Mon, Feb 9, 2015 at 5:39 PM, Erik Jan de Wit <notifications@github.com>
wrote:

> why not have the window part of the table show the current released
> support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/487#issuecomment-73541291>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by abstractj** [comment]
@edewit who had already tested https://www.nuget.org/packages/aerogear-windows-oauth2/ and http://plugins.cordova.io/#/package/org.jboss.aerogear.cordova.oauth2 before you release?

Which features are we able to mark as done/stable? Please, understand that "OAuth2 for Windows Phone" is generic, and I would like to understand what we already accomplished or not.

Until we figure this out, I fine on merging this PR and update later or hold it until we get more feedback.

**Comment by edewit** [comment]
@matzew updated your pr https://github.com/matzew/aerogear.org/pull/9

**Comment by abstractj** [comment]
@edewit your highness, could you please give me the joy of having your answers?

**Comment by matzew** [comment]
* QE tested the oauth cordova plugin
* windows was tested by @secondsun

**Comment by secondsun** [comment]
@matzew Actually I could never get it working in Windows before other things (hoildays, sync, demo, AGDROID 2.0) ate me.  So while I "tested" it I never +1'd it.

**Comment by matzew** [comment]
@secondsun ok, thanks for the heads up. But this table keeps the Windows stuff at minus (-).

**Comment by matzew** [comment]
@secondsun that said, @edewit filed a PR for this PR here:

https://github.com/matzew/aerogear.org/pull/9

As far as I understand @secondsun (got nothing working on Windows), I think it's safe for now, to ignore https://github.com/matzew/aerogear.org/pull/9 and just merge this one.

Perhaps @stribny has a comment on Windows as well ?

**Comment by edewit** [comment]
@secondsun had one issue with it, but also @corinnekrych tested it successfully

**Comment by edewit** [comment]
And @secondsun didn't file a issue so....

**Comment by secondsun** [comment]
@edewit Right I didn't file an issue.  I was mostly correcting @matzew and saying I didn't test it.  @corinnekrych did and I trust her judgment.

**Comment by matzew** [comment]
merging _this_ PR.

**Comment by matzew** [comment]
@sebastienblanc @edewit regarding the Windows 'check marks' feel free to send an update, on a different PR. 

The finger pointing here was not helpful for me, to understand the right status of Windows, that's why I keep the status of our annoncement from last week - but that does not mean that there can't be a PR to update the table...

**Pull request merged**
