### PR TITLE
UI related changes for 1.1.0 UPS guide updates

### PR DESCRIPTION
**Pull request by matzew**
@danielpassos @corinnekrych @sebastienblanc 

please review and let me know how you like the changes

### CODE REVIEW

**Comment by sebastienblanc** [comment]
:eyes:

**Comment by matzew** [comment]
@sebastienblanc mind to check the last commit?

Besides that a few words on the analytic UI is still missing

**Comment by sebastienblanc** [comment]
:eyeglasses:

**Comment by matzew** [comment]
@sebastienblanc thanks dude!

**Comment by sebastienblanc** [comment]
@matzew and btw +1 on your latest commit !

**Comment by matzew** [comment]
thanks @sebastienblanc !

**Pull request merged**
