### PR TITLE
Android 2.1

### PR DESCRIPTION
**Pull request by secondsun**
Should be a quickie review.  These are all of the useful bits set to point to 2.1.0 instead of 2.1.0, adding in the sync module, and adding in the updated java docs.

### CODE REVIEW

**Comment by secondsun** [comment]
@qmx @matzew :eyes: ?

**Comment by lfryc** [comment]
:+1:

**Comment by matzew** [comment]
@secondsun any chance to get a blog post type of announcement on aerogear.org, like we do on other components ?

**Comment by secondsun** [comment]
@matzew Check out my other PR https://github.com/aerogear/aerogear.org/pull/568

**Pull request merged**
