### PR TITLE
Adding little Android announcement entry

### PR DESCRIPTION
**Pull request by matzew**
@danielpassos @secondsun can you review and merge (to master and production)?

### CODE REVIEW

**Comment by secondsun** [comment]
+1 @danielpassos ?

**Comment by danielpassos** [comment]
:+1:

**Comment by danielpassos** [comment]
I've merge on master. Let me check on staging before to merge on production

**Comment by matzew** [comment]
I think staging is broken since we have the SSL certificate in place. I
pinged IT guys about this. The work around would be a local build

On Tue, Jan 20, 2015 at 1:34 AM, Daniel Passos <notifications@github.com>
wrote:

> I've merge on master. Let me check on staging before to merge on production
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/466#issuecomment-70585379>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by edewit** [comment]
@matzew didn't work in chrome, but I could load it in Safari seems that that latter is a bit more lenient.

**Comment by matzew** [comment]
Firefox same - not possible to view the staging repo. Good to know that
Safari is actually good at something :-)

Anyways, I will wait what I hear back from the IT guys - but that reply
should not block any updates to production branch ;-)

On Tue, Jan 20, 2015 at 7:53 AM, Erik Jan de Wit <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> didn't work in chrome, but I could
> load it in Safari seems that that latter is a bit more lenient.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/466#issuecomment-70611875>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request merged**
