### PR TITLE
Adding initial OAuth2 landing page

### PR DESCRIPTION
**Pull request by matzew**
Adding a first and initial landing page for our OAuth2 module.

The page links to the different repos and gives some updates. As we continue the work on OAuth2 (e.g. releases), the content will get updated (e.g. links to the downloads etc)

### CODE REVIEW

**Comment by matzew** [comment]
@danielpassos @corinnekrych @edewit @abstractj  mind to review this initial landing page for OAuth2 ?

**Comment by danielpassos** [comment]
:+1:  lgtm

**Comment by corinnekrych** [comment]
:eyes:

**Comment by edewit** [comment]
:+1:

**Comment by corinnekrych** [comment]
:+1:

**Comment by danielpassos** [comment]
Landed at 3b7e49bb7f9aaf8cd2caee9fdc3cbc8d77316225

**Pull request closed without merging**
