### PR TITLE
AeroGear Cordova announcement

### PR DESCRIPTION
**Pull request by abstractj**
@matzew @edewit @balunasj could you please, review?

### CODE REVIEW

**Comment by matzew** [comment]
:+1: to :unlock: this :newspaper:

**Comment by edewit** [comment]
I like how you've put this :+1:

**Comment by matzew** [comment]
I am happy to push to master/prod. and do some tweet afterwards to spread
the secured love

On Fri, May 29, 2015 at 8:23 AM, Erik Jan de Wit <notifications@github.com>
wrote:

> I like how you've put this [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/589#issuecomment-106705632>
> .
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
thanks, landed in https://github.com/aerogear/aerogear.org/commit/a0b4b229417e6699f58dc5ad083694eabe386ff3

**Pull request closed without merging**
