### PR TITLE
Removing old User Guides

### PR DESCRIPTION
**Pull request by lholmquist**
as discussed on the ML,  http://lists.jboss.org/pipermail/aerogear-dev/2015-January/010503.html

### CODE REVIEW

**Comment by danbev** [comment]
:+1:

**Comment by corinnekrych** [comment]
@lholmquist as discussed we still need /docs/guides/GetStartedwithAeroGearandXcodeTemplate as it's referenced by /ios/index-ios-1.X.html. I've created a PR https://github.com/lholmquist/aerogear.org/pull/1 (on you PR) to bring back (and I moved its location).

also it will be nice if somebody brave enough :) could clear img/ folder. Lots of images are not needed anymore like: img/html5_wiz_01.png, others related to Android IDE are not also left-over not referenced any more.

**Comment by lholmquist** [comment]
@corinnekrych i updated the PR with your PR added in,  and rebased

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
