### PR TITLE
Removing duplicated roadmap files and linking to JIRA for specifics

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by abstractj** [comment]
-1 on removing the security roadmap, atm.

**Comment by matzew** [comment]
I see, the security roadmap also lists potential items, let me update this
PR

perhaps at some point in the future, we can be fully based on JIRA

On Mon, Jan 5, 2015 at 3:50 PM, Bruno Oliveira <notifications@github.com>
wrote:

> -1 on removing the security roadmap, atm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/455#issuecomment-68717298>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by abstractj** [comment]
@matzew if this is a team consensus I will do for sure.

**Comment by matzew** [comment]
closing for now, this needs a bit more work

**Pull request closed without merging**
