### PR TITLE
AGCORDOVA-162 added Xcode 8 information

### PR DESCRIPTION
**Pull request by jcesarmobile**
added Xcode 8 information about the .entitlements file

### CODE REVIEW

**Comment by corinnekrych** [comment]
@jcesarmobile I'd move `### Xcode 8 setup` before https://github.com/jcesarmobile/aerogear.org/blob/758b0a75fde23c4443800410d266f5017b21a1e4/docs/guides/aerogear-cordova/AerogearCordovaPush.asciidoc#to-unregister-only-available-on-android so it belong to the other section not embedded in `To unregister (only available on Android)`

apart from that +1

**Comment by jcesarmobile** [comment]
It's supposed to be a new title after `To unregister`, as unregister is still part of the SDK. 
Maybe make it bigger with just 2 `##` instead of 3?

**Comment by corinnekrych** [comment]
Oki fine too

**Comment by jcesarmobile** [comment]
done

**Pull request merged**
