### PR TITLE
Make News work: blog aggregation, filtering, tagcloud

### PR DESCRIPTION
**Pull request by lfryc**
* registered missing blogs
* jquery-based javascript that made the news interactive

Fixes:
* https://issues.jboss.org/browse/AEROGEAR-1554
* https://issues.jboss.org/browse/AEROGEAR-551
* https://issues.jboss.org/browse/AEROGEAR-1603

### CODE REVIEW

**Comment by lfryc** [comment]
Deployed here: http://staging-aerogearsite.rhcloud.com/news/

**Comment by lfryc** [comment]
@abstractj @andresgalante would you mind to review?

**Comment by abstractj** [comment]
Loved it! +1 for please, please merge!

**Comment by lfryc** [comment]
Merging...

**Comment by andresgalante** [comment]
:+1: too bad I am not in jboss planet :)

**Comment by lfryc** [comment]
@andresgalante - let's propose your blog: https://planet.jboss.org/manage/feed/new

**Comment by lfryc** [comment]
Thanks guys!

**Pull request merged**
