### PR TITLE
Updating DataSync specification.

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
The current DataSync specification contains information that is
outdated. The goal of this pull request is to document only what is
currently exists.

Modifications:
Updated the main docs/specs/aerogear-data-sync/ page so that it now only
contains a features section followed by links to the message format, the
java server api, and the java client api.

JIRA:
https://issues.jboss.org/browse/AGSYNC-31

### CODE REVIEW

**Comment by danbev** [comment]
@danielpassos @matzew Would you guys mind to review?

**Comment by matzew** [comment]
A few thoughts (need to actually read more of it), but instead of adding handwritten files for `aerogear-sync-client-java-api` and `aerogear-sync-server-api`, I think it would be way better to put the info into the JavaDocs of those APIs and have them served from aerogear.org

**Comment by danbev** [comment]
@matzew Perhaps the name of the files are miss leading. The content of these files are for the "higher" level concepts of the Java Client/Server. But I can put the same information in a package-info.java, one for the server and one for the client and just link to them.

**Comment by matzew** [comment]
`package-info.java` would be good place for that. I am a bit worried we add
more and more "specs" on the site, that are hard to maintain. While JavaDoc
may be easier to update, since that's directly part of the code. Just a
thought

On Tue, Feb 3, 2015 at 12:06 PM, Daniel Bevenius <notifications@github.com>
wrote:

> @matzew <https://github.com/matzew> Perhaps the name of the files are
> miss leading. The content of these files are for the "higher" level
> concepts of the Java Client/Server. But I can put the same information in a
> package-info.java, one for the server and one for the client and just link
> to them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/482#issuecomment-72632626>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by danbev** [comment]
@matzew Sounds good. Let me try that and see what it would look like.

**Comment by matzew** [comment]
Perfect! Besides that, I think that `aerogear-data-sync` and `aerogear-sync-data-format` are exactly those things we really need here, especially a generic doc on details of the wire-protocol / message format

**Comment by danbev** [comment]
@matzew I've updated this PR with a suggestion for pointing to javadocs instead. Let me know if this is what you had in mind?

**Comment by matzew** [comment]
that's good .

merged it

**Pull request merged**
