### PR TITLE
Removing Sync roadmap, since covered in JIRA

### PR DESCRIPTION
**Pull request by matzew**
cleaning up the duplicated SyncRoadmap, since all JIRAs and their descriptions are just duplicated here on this doc

### CODE REVIEW

**Comment by matzew** [comment]
@danbev @lholmquist can you review and merge ?

**Comment by edewit** [comment]
there is a link on AeroGeariOS.asciidoc pointing to this document

**Comment by matzew** [comment]
@edewit thanks

**Comment by matzew** [comment]
the `AeroGearRoadMap` was removed before, and I updated the iOS section, to point to the proper JIRA instead. @corinnekrych

**Comment by danbev** [comment]
:+1:

**Comment by corinnekrych** [comment]
+1

**Comment by lholmquist** [comment]
+1 merging

**Pull request merged**
