### PR TITLE
iOS 2.2 post

### PR DESCRIPTION
**Pull request by corinnekrych**
@cvasilak mind to review?
to be merged next week to match sync1.0.0.alpa.1 announcement

### CODE REVIEW

**Comment by lfryc** [comment]
Sync blog is prepared in https://github.com/aerogear/aerogear.org/pull/552, can I merge them together?

**Comment by lfryc** [comment]
If this is for next week, we could close it and reopend next week so we won't accidentally merge it?

**Comment by matzew** [comment]
+1000

On Thu, Mar 12, 2015 at 1:13 PM, Lukáš Fryč <notifications@github.com>
wrote:

> If this is for next week, we could close it and reopend next week so we
> won't accidentally merge it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear.org/pull/551#issuecomment-78468710>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by matzew** [comment]
review can be handled on a branch, no need to trigger PR

On Thu, Mar 12, 2015 at 1:22 PM, Matthias Wessendorf <matzew@apache.org>
wrote:

> +1000
>
> On Thu, Mar 12, 2015 at 1:13 PM, Lukáš Fryč <notifications@github.com>
> wrote:
>
>> If this is for next week, we could close it and reopend next week so we
>> won't accidentally merge it?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aerogear/aerogear.org/pull/551#issuecomment-78468710>
>> .
>>
>
>
>
> --
> Matthias Wessendorf
>
> blog: http://matthiaswessendorf.wordpress.com/
> sessions: http://www.slideshare.net/mwessendorf
> twitter: http://twitter.com/mwessendorf
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Pull request closed without merging**
