### PR TITLE
windows frontpage

### PR DESCRIPTION
**Pull request by edewit**
added windows on the front page of the site

### CODE REVIEW

**Comment by matzew** [comment]
Not sure if we do need a license: http://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx

yikes... :-(

**Comment by matzew** [comment]
https://github.com/edewit/aerogear.org/blob/windows/img/windows-logo.png

this is _clearly_ not the original windows logo - I am pretty sure we are OK to use it. I did follow up w/ legal internally

**Comment by abstractj** [comment]
@edewit @matzew landed

**Comment by matzew** [comment]
For the record, I haven't yet gotten any legal approval for the usage of the Windows logo. But I am in contact with our legal team. While it looks to me, as said earlier (but I am not a lawyer) it is _OK_ to use the logo, it may be the case to get rid of it, asap. But I have not yet gotten any legal approval for the usage of the logo.

**Comment by edewit** [comment]
If there is any legal issue we can quickly revert this commit, we are not disrespecting any copyrights on purpose here.

**Comment by matzew** [comment]
Right - I am on the same page here

**Pull request closed without merging**
