### PR TITLE
update sync-links+oauth2 minor release

### PR DESCRIPTION
**Pull request by cvasilak**
@corinnekrych mind to review? 

>[NOTE]
once Podfile's update on ios-cookbook [PR#74](https://github.com/aerogear/aerogear-ios-cookbook/pull/74) and [PR#73](https://github.com/aerogear/aerogear-ios-cookbook/pull/73) are merged, a ```0.2.1``` tag will be done on repo, that reflects the links to cookbooks demos used in this PR

### CODE REVIEW

**Comment by lfryc** [comment]
Ready to be merged? /cc @corinnekrych

**Comment by corinnekrych** [comment]
+1

**Comment by matzew** [comment]
@cvasilak can you rebase?

**Comment by cvasilak** [comment]
closing this opened https://github.com/aerogear/aerogear.org/pull/564 that goes against ```master``` branch

**Pull request closed without merging**
