### PR TITLE
removed all absolute links

### PR DESCRIPTION
**Pull request by edewit**
When running the site locally it's not cool to suddenly find yourself on aerogear.org

### CODE REVIEW

**Comment by edewit** [comment]
@lfryc WDYT

**Comment by matzew** [comment]
:+1:

**Comment by lfryc** [comment]
:+1: merging

**Comment by lfryc** [comment]
:+1: merged

**Comment by lfryc** [comment]
https://github.com/aerogear/aerogear.org/commit/0f04ad9b7a7583c0df6b0f5c27e1b9c0e196da3b

**Pull request closed without merging**
