### PR TITLE
Upgrade to Jekyll 3, plus update asciidoctor

### PR DESCRIPTION
**Pull request by abstractj**
This PR is to fix the encoding bug on Jekyll

### CODE REVIEW

**Comment by lholmquist** [comment]
built fine. 
:+1: 

there was a deprecation notice:  

` Deprecation: Collection#each should be called on the #docs array directly.
                    Called by /Users/lholmquist/develop/projects/aerogear.org/_plugins/rss_atom_posts.rb:57:in `generate'.`

but i'm sure it's fine

**Comment by lholmquist** [comment]
should mention my ruby version:  ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.3.0]

**Comment by abstractj** [comment]
@lholmquist I managed to fix most of the deprecation notices at the RSS plugin. But was afraid of change this line of code and mess it up :smiley_cat:

**Comment by matzew** [comment]
:+1: 

@lholmquist fine in moving foward here ? this is now working, thanks to the awesome @abstractj

**Comment by lholmquist** [comment]
:rocket: :guitar: :tada:

**Pull request merged**
