### PR TITLE
Adding JS API docs for the 2.1.0 release

### PR DESCRIPTION
**Pull request by lholmquist**
This updates the Docs for AeroGear.js for the forth coming 2.1.0 release

@lfryc @sebastienblanc :eyes: ?

### CODE REVIEW

**Comment by lfryc** [comment]
:eyes: 

I wonder if we should add an explanation and link to Diff Sync section on API Docs index page, will send PR.

**Comment by lholmquist** [comment]
@lfryc yea,  that is probably a good idea :)

**Comment by lfryc** [comment]
@lholmquist sent suggested changes here: https://github.com/aerogear/aerogear-js/pull/167

**Comment by lholmquist** [comment]
@lfryc merged those from aerogear/aerogear-js#167 and update the PR, which i also squashed

**Comment by lholmquist** [comment]
@lfryc i should be moving this to the new design branch?

**Comment by lfryc** [comment]
Landed: https://github.com/aerogear/aerogear.org/commit/27907298aed4de7e6666c64d9d7b7b0dcdcbd0cc

**Pull request closed without merging**
