### PR TITLE
adds front matter on news post

### PR DESCRIPTION
**Pull request by andresgalante**
@corinnekrych can you review this one please?

### CODE REVIEW

**Comment by corinnekrych** [comment]
+1

**Comment by lfryc** [comment]
One more change I would suggest is changing the greeting and wording so the post excerpt appears nicely on `News` page:

Right now we have: `Hello AeroGear Community`

What would be better: `The iOS team is happy to announce the version 2.2 of AeroGear iOS libraries that includes Data Sync feature for iOS.`

wdyt @corinnekrych @andresgalante ?

**Comment by corinnekrych** [comment]
+1

**Comment by lfryc** [comment]
@corinnekrych send a PR here to update @andresgalante updates :-)

https://github.com/andresgalante/aerogear.org/pull/2

Could you please review that?

**Comment by andresgalante** [comment]
:+1: good idea on having a longer excerpt

**Comment by lfryc** [comment]
:rocket: landed: https://github.com/aerogear/aerogear.org/commit/1907d27ddf3db6cb49d1a24eacb46fda5098a2cf

**Pull request closed without merging**
