### PR TITLE
fixing iOS related issues

### PR DESCRIPTION
**Pull request by cvasilak**
this PR fixes the issues discovered on the new site and be mentioned on the [ML discussion](http://aerogear-dev.1069024.n5.nabble.com/aerogear-dev-New-Site-Status-td10905.html#a10925)

@corinnekrych mind to look? 

https://issues.jboss.org/browse/AEROGEAR-1644

### CODE REVIEW

**Comment by lfryc** [comment]
Thanks @cvasilak , I will take a look...

**Comment by lfryc** [comment]
I deployed the site with @cvasilak changes here: http://staging-aerogearsite.rhcloud.com/getstarted/guides/

**Comment by lfryc** [comment]
@cvasilak I would move iOS 2.x from First Steps to AeroGear SDK Guides.

Do we have any "First Steps with iOS" guide? Maybe something like iOS 1.6.x Getting Started with XCode Template.

----

For consistency with Downloads, I would either remove iOS 1.x from Guides (just provide a link?).
Alternatively, we can add iOS guides to the main Guides page.

**Comment by cvasilak** [comment]
@lfryc have updated based on your feedback thank you!

>> @cvasilak I would move iOS 2.x from First Steps to AeroGear SDK Guides.
done

>> Do we have any "First Steps with iOS" guide? Maybe something like iOS 1.6.x Getting Started with XCode Template.
not so far apart from guides for each respective library

>>For consistency with Downloads, I would either remove iOS 1.x from Guides (just provide a link?).
>>Alternatively, we can add iOS guides to the main Guides page.
done, added link

some further changes:
-further added headers on the old iOS 1.6.x guides pages splitting to Fist steps/Core/Security/ in order to be mentally linked with our new stuff and easily spotted if followed.
-removed httpstub library link since it will be deprecated.

@lfryc @corinnekrych let me know what you think

**Comment by lfryc** [comment]
Question: we could do the same as we did in [Docs](http://staging-aerogearsite.rhcloud.com/docs/specs/) - [put security-related Guides](http://staging-aerogearsite.rhcloud.com/getstarted/guides/) for SDKs into both sections, AeroGearSDK and AeroGearSecurity - it's a duplication but for a good reason.

**Comment by lfryc** [comment]
Btw refreshed the staging with latest of this PR: http://staging-aerogearsite.rhcloud.com/getstarted/guides/

**Comment by lfryc** [comment]
@cvasilak but otherwise looks good! we can also resolve my previous concern once we will be finishing and checking consistency

**Comment by lfryc** [comment]
@corinnekrych do you want to take a look or should I merge?

**Comment by lfryc** [comment]
btw pages for AG iOS 1.6.x downloads/guides need styling, but I will resolve that later

**Comment by cvasilak** [comment]
@lfryc wrote:
>we could do the same as we did in Docs - put security-related Guides for SDKs into both sections, AeroGearSDK and AeroGearSecurity - it's a duplication but for a good reason. Wdyt?

sure I like it too, have updated PR :+1:

**Comment by lfryc** [comment]
merging...

**Pull request merged**
