### PR TITLE
New design improvements

### PR DESCRIPTION
**Pull request by lfryc**
* Changed `AeroGearCore` to `AeroGearSDK` in headers in Guides and Docs.
* moved Roadmap to own tab in Navigation

Please review:
* http://staging-aerogearsite.rhcloud.com/getstarted/guides/
* http://staging-aerogearsite.rhcloud.com/docs/specs/
* Road Map in Navigation

Resolving:
https://issues.jboss.org/browse/AEROGEAR-1599
https://issues.jboss.org/browse/AEROGEAR-1598

### CODE REVIEW

**Comment by lfryc** [comment]
@matzew could you please quickly review sections as outlined above?

http://staging-aerogearsite.rhcloud.com/

**Comment by matzew** [comment]
@lfryc is it just me? or is the background image load pretty slow?

**Comment by matzew** [comment]
@andresgalante, @lfryc lets please remove the 

```
"Aerogear is the best thing that happend in my life! Absolut happend in my life! Absolt happend in my life! Absoltely fantastic."
Name Lastname, Company Name
```

section. ATM we do not have such a statement, once we have that we can revisit (I also think the current position is not right for that)

**Comment by matzew** [comment]
@lfryc can you remove " AeroGear OAuth2 - 1.0.0 (January 2015)" ? - has been released

**Comment by matzew** [comment]
* Road Map in Navigation :+1: (besides the comment above)

**Comment by matzew** [comment]
* http://staging-aerogearsite.rhcloud.com/getstarted/guides/
on the 'iOS 1.X' we list:
* Pipe and Pipeline
* Pagination
* Store and DataManager

@corinnekrych do we want to have something for iOS 2.x ?

**Comment by lfryc** [comment]
@matzew Andres is still working on home page, this was rather specifically meant as for the outlined sections.

**Comment by matzew** [comment]
@lfryc "AeroGearPush Guides"
* Push Notification Message Format
* Client Registration details

are not part of the UPS guide/book

**Comment by matzew** [comment]
* http://staging-aerogearsite.rhcloud.com/docs/specs/

like it! especially the `Experimental` on sync /cc @danbev :-)

**Comment by lfryc** [comment]
I believe Christos took care of iOS 2.x here: https://github.com/aerogear/aerogear.org/pull/505
I'm going to review it now.

**Comment by lfryc** [comment]
Removed OAuth2 from the Road Map: http://staging-aerogearsite.rhcloud.com/docs/planning/

**Comment by lfryc** [comment]
Thanks for checking @matzew !

**Pull request merged**
