### PR TITLE
AGDIGGER-196 digger initial docs

### PR DESCRIPTION
**Pull request by aliok**
JIRA: AGDIGGER-196

Do the things in README.md to verify locally. However, things didn't work with Ruby 2.1.2 for me but they worked with Ruby 2.2.2.

Note the known issues and missing things in AeroGear.org **Digger related things**: https://issues.jboss.org/browse/AGDIGGER-195

Note the known issues and missing things in AeroGear.org **in general**: https://issues.jboss.org/browse/AEROGEAR-1760

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@aliok I had some trouble getting to the existing documentation. eg. installation, admin etc. Could we also get a link for that?

**Comment by laurafitzgerald** [comment]
@aliok as part of this pr can we get an extra build option added to the table in this page https://github.com/aerogear/aerogear.org/blob/Build-Farm-2/docs/digger/developer/jenkins-build.asciidoc
platform should be included there

**Comment by aliok** [comment]
@laurafitzgerald I updated the docs page to have links to Digger guides. Thanks for the suggestion.

About "platform" param: that's not in that table because it only explains "Building iOS Applications". That part of the documentation needs some improvement. What do you think?

**Comment by aliok** [comment]
@laurafitzgerald ok, created https://issues.jboss.org/browse/AGDIGGER-211

**Pull request merged**
