### PR TITLE
RHMAP-18826 update macOS variables/review, from 18330/17003

### PR DESCRIPTION
**Pull request by pmacko1**
https://github.com/aerogear/aerogear.org/pull/683/ see comments (if present)

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@pmacko1 I could be wrong but it looks like this file that you have changed is not being referenced in any of the sections?

**Comment by pmacko1** [comment]
@laurafitzgerald mr #683 have it referenced, i have renamed the file

**Comment by laurafitzgerald** [comment]
@pmacko1 could you rebase this one so that I can view the diff again?

**Comment by pmacko1** [comment]
closing, this is a mess. will resolve in another pr

**Pull request closed without merging**
