### PR TITLE
Refactors all push guides to a single document AEROGEAR-1664

### PR DESCRIPTION
**Pull request by andresgalante**
@lfryc what do you think?

http://issues.jboss.org/browse/AEROGEAR-1664

### CODE REVIEW

**Comment by lfryc** [comment]
@andresgalante 

I'm getting these warnings:

````
asciidoctor: WARNING: docs/unifiedpush/aerogear-push-ios/unified-push-server.asciidoc: line 14: include file not found: /home/lfryc/workspaces/aerogear/aerogear-site/docs/unifiedpush/aerogear-push-ios/docs/unifiedpush/include--register-app.asciidoc
asciidoctor: WARNING: docs/unifiedpush/aerogear-push-chrome/register-device.asciidoc: line 18: include file not found: /home/lfryc/workspaces/aerogear/aerogear-site/docs/unifiedpush/aerogear-push-chrome/docs/unifiedpush/include--register-app.asciidoc
asciidoctor: WARNING: docs/unifiedpush/aerogear-push-js/unifiedpush-server.asciidoc: line 7: include file not found: /home/lfryc/workspaces/aerogear/aerogear-site/docs/unifiedpush/aerogear-push-js/docs/unifiedpush/include--register-app.asciidoc
asciidoctor: WARNING: docs/unifiedpush/aerogear-push-windows/register-device.asciidoc: line 8: include file not found: /home/lfryc/workspaces/aerogear/aerogear-site/docs/unifiedpush/aerogear-push-windows/docs/unifiedpush/include--register-app.asciidoc
````

**Comment by lfryc** [comment]
But otherwise it looks awesome @andresgalante !

**Comment by andresgalante** [comment]
@lfryc sorry :( I'll remove the warnings

**Comment by lfryc** [comment]
Merged here: https://github.com/aerogear/aerogear.org/commit/67b398d4c89e943ce5a020ac661c144e0fe04c33

Thanks @andresgalante !!

**Pull request closed without merging**
