### PR TITLE
added missing UPS specs: Message Format and Client Registration to Docs ...

### PR DESCRIPTION
**Pull request by lfryc**
http://aerogear-dev.1069024.n5.nabble.com/aerogear-dev-New-Site-Design-Status-update-Request-for-reviews-tp11091p11093.html

### CODE REVIEW

**Comment by lfryc** [comment]
@matzew :

:eyes: :question: 

:+1:  / :-1: :question:

**Comment by matzew** [comment]
@lfryc :+1: :100:

**Comment by lfryc** [comment]
:rocket: :dart: https://github.com/aerogear/aerogear.org/commit/d3d411070c26ecca1b696ac5c3b65841a36178d0

**Comment by matzew** [comment]
:tada:

**Comment by abstractj** [comment]
@lfryc I guess it was landed here https://github.com/aerogear/aerogear.org/commit/d3d411070c26ecca1b696ac5c3b65841a36178d0. But not closed, I'm doing it right now, but feel free to reopen if I'm wrong.

**Comment by matzew** [comment]
@abstractj we focused on emojis :wink: 

thanks for :closed_book:

**Comment by abstractj** [comment]
@matzew :+1: :fireworks: :baby_chick: :cactus: :cake: :camel: :hamburger: :hand:

**Pull request closed without merging**
