### PR TITLE
UPS & Keycloak decoupling

### PR DESCRIPTION
**Pull request by abstractj**
@secondsun @danbev @lfryc @sebastienblanc only if you get the chance, could you :pray: review?

### CODE REVIEW

**Comment by danbev** [comment]
:eyes:

**Comment by pmacko1** [comment]
@secondsun @laurafitzgerald could you take a look at this old pr and tag approp ppl?

**Comment by laurafitzgerald** [comment]
@pmacko1 I have no knowledge around Keycloak and UPS so would not be the best to review this. It's possible this one is out of date. Best to send it to the aerogear-dev mailing list and see if anyone with the knowledge would check this one.

**Comment by abstractj** [comment]
I'm closing this change, since this became a very old change. Feel free to get the code if needed.

**Pull request closed without merging**
