### PR TITLE
AGDroid 2.0.0

### PR DESCRIPTION
**Pull request by danielpassos**

### CODE REVIEW

**Comment by danielpassos** [comment]
I'm not sure what is the best way to show all modules in Android land page. I'm open for suggestions

**Comment by danielpassos** [comment]
@qmx @matzew @secondsun Could you review it?

**Comment by matzew** [comment]
@secondsun any comment on the "starting with AeroGear Android 2.0.0..." comment ?

**Comment by secondsun** [comment]
We should just copy the release notes from the blog instead of linking to the blog post.

**Comment by secondsun** [comment]
The specs page lists Store 2.0.0-alpha.1

**Comment by danielpassos** [comment]
@secondsun Fixed spec page

**Comment by danielpassos** [comment]
@matzew Done!

**Comment by matzew** [comment]
cool

**Pull request merged**
