### PR TITLE
Add code owner

### PR DESCRIPTION
**Pull request by camilamacedo86**
# What
Add code owner definition/description

screen shot 2018-10-10 at 15 18 06

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
@camilamacedo86 I saw you pinged me on the trello card. wdyt about putting this under the `Contributing to AeroGear` section?

**Comment by camilamacedo86** [comment]
@laurafitzgerald It is under the Contributing to AeroGear section. The "Source Repository" appears there and the Code Owner is a subsection of it. Is it make sense? Wdyt? Where do think it is better?

**Comment by laurafitzgerald** [comment]
@camilamacedo86 sure, that makes sense where you have it. I was travelling yesterday so didn't have the chance to build it. It looks good where you have it. The only comment is that I think the Buttons for the repo should be moved up before the Code Owner section as they are linking to the Source Repos which is covered in the first paragraph in the screenshot you provided.

**Comment by camilamacedo86** [comment]
I will do it and let you know.

**Comment by matzew** [comment]
@camilamacedo86 I am not really active on the development - no need to include me on reviews

**Comment by camilamacedo86** [comment]
@laurafitzgerald it was changed as you requested and the first comment has the image with this result.

**Pull request merged**
